title: CS Reading Group
description: CS adjacent reading group
author: CS Reading Group
github: https://github.com/csreadinggroup
about: We are a journal club started in June 2020 by a bunch of computer science and computer science-adjacent undergraduates. 

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://hkust-green-reading.github.io"

urls:
    - text: Papers
      url: /papers
    - text: By Category
      url: /category/all

url: "https://hkust-green-reading.github.io"
baseurl: ""
paginate: 50
per_page: 50
paginate_path: "papers/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
