title: ESG Reading Group
description: ESG reading group
author: ESG Reading Group
github: https://github.com/csreadinggroup
about: started in Nov 2023. 

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://murasamess.github.io/category/algorithms"

urls:
    - text: Papers
      url: /papers
    - text: By Category
      url: /category/all

url: "https://murasamess.github.io/category/algorithms"
baseurl: ""
paginate: 50
per_page: 50
paginate_path: "papers/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
